#!/usr/bin/python3

from optparse import OptionParser
import sys
from snap_seeds import check_snap_seeds, get_supported_model_series


def main():
    parser = OptionParser(
        usage="Usage: %prog [options] [series1] ... [seriesN]")
    parser.add_option(
        "-m", "--models-path", metavar="MODELS_PATH",
        default='.')
    parser.add_option(
        "--dry-run", dest="dry_run", action="store_true")
    opts, args = parser.parse_args()
    # If no series are specified, check all supported series.
    if len(args) > 0:
        series = args
    else:
        series = get_supported_model_series()
    # Run the check for every defined series.
    return_value = 0
    for s in series:
        if check_snap_seeds(s, opts.models_path, dry_run=opts.dry_run):
            return_value = 1
    return return_value


if __name__ == '__main__':
    sys.exit(main())